In [20]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [21]:
df =pd.read_csv('heart.csv')

In [22]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [24]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
172   56    1   1       120   240    0        1      169      0      0.0   
128   52    1   2       138   223    0        1      169      0      0.0   
363   53    1   2       130   246    1        0      173      0      0.0   
636   59    0   0       174   249    0        1      143      1      0.0   
798   59    1   3       170   288    0        0      159      0      0.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
299   52    1   1       120   325    0        1      172      0      0.2   
534   54    0   2       108   267    0        0      167      0      0.0   
584   55    1   0       132   353    0        1      132      1      1.2   
493   55    1   0       132   353    0        1      132      1      1.2   
527   62    0   0       124   209    0        1      163      0      0.0   

     slope  ca  thal  
172      0   0     2  
128      2   4     2  
363      2   3     2  
636      1   0     2  
798      1   0     3  
..     ...  ..   ...  
299      2   0     2  
534      2   0     2  
584      1   1     3  
493      1   1     3  
527      2   0     2  

[820 rows x 13 columns]

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [26]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [27]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [28]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

# Accuracy Score

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy Score of Logistic Regression:",accuracy_score(y_test,y_pred1))
print("Accuracy Score of Decision Treee:",accuracy_score(y_test,y_pred2))

Accuracy Score of Logistic Regression: 0.8390243902439024
Accuracy Score of Decision Treee: 0.9804878048780488


# Confusion Matrix

In [30]:
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [10, 90]], dtype=int64)

In [31]:
confusion_matrix(y_test,y_pred2)

array([[101,   4],
       [  0, 100]], dtype=int64)

# Precision, Recall Score, F1 score

In [37]:
from sklearn.metrics import precision_score,recall_score, f1_score

print("Precision LR: ",precision_score(y_test,y_pred1))
print("Recall LR: ",recall_score(y_test,y_pred1))
print("F1 score LR: ",f1_score(y_test,y_pred1))

Precision LR:  0.7964601769911505
Recall LR:  0.9
F1 score LR:  0.8450704225352113


In [38]:
print("Precision DT: ",precision_score(y_test,y_pred2))
print("Recall DT: ",recall_score(y_test,y_pred2))
print("F1 score DT: ",f1_score(y_test,y_pred2))

Precision DT:  0.9615384615384616
Recall DT:  1.0
F1 score DT:  0.9803921568627451


In [34]:
precision_score(y_test,y_pred1, average=None)

array([0.89130435, 0.79646018])

In [35]:
precision_score(y_test,y_pred2, average=None)

array([1.        , 0.96153846])